# Generated by Django 6.0.1 on 2026-01-28 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialistservice',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.specialistprofile'),
        ),
        migrations.AddConstraint(
            model_name='specialistservice',
            constraint=models.UniqueConstraint(fields=('specialist', 'service'), name='unique_specialist_service'),
        ),
    ]
