# Generated by Django 6.0.1 on 2026-02-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
