# Generated by Django 6.0.1 on 2026-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_alter_service_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialistservice",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
