# Generated by Django 6.0.1 on 2026-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientwallettransaction",
            name="balance_after",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
