# Generated by Django 6.0.1 on 2026-02-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        ("wallets", "0002_clientwallettransaction_balance_after"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="clientwallettransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("service_record__isnull", True), ("type", 1)),
                    models.Q(("service_record__isnull", False), ("type__in", [2, 3])),
                    _connector="OR",
                ),
                name="wallet_transaction_service_record_constraint",
            ),
        ),
    ]
